# Generated by Django 4.1.7 on 2023-05-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('nome', models.CharField(default='', max_length=45)),
                ('descricao', models.TextField(blank=True, max_length=520, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('endereco', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default='Sem nome', max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('oferta', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Weblist.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('ingreientes', models.TextField(blank=True, max_length=1000, null=True)),
                ('modoPreparo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user')),
                ('idproduto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Weblist.produto')),
                ('idreceita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.receita')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user'),
        ),
        migrations.AddField(
            model_name='produto',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.mercado'),
        ),
        migrations.AddField(
            model_name='mercado',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user'),
        ),
        migrations.CreateModel(
            name='ListaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user')),
                ('idlista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.lista')),
                ('idproduto', models.ManyToManyField(to='Weblist.produto')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.user'),
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('historicoPreco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Weblist.produto')),
            ],
        ),
    ]
