# Generated by Django 4.1.7 on 2023-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='ingreientes',
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
