# Generated by Django 4.1.7 on 2023-05-21 12:52

import Weblist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0002_remove_receita_ingreientes_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Weblist.models.upload_image_receita),
        ),
    ]
