# Generated by Django 4.1.7 on 2023-05-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0003_receita_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='idproduto',
            field=models.ManyToManyField(to='Weblist.produto'),
        ),
    ]
