# Generated by Django 4.1.7 on 2023-05-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0004_receita_idproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
