# Generated by Django 4.1.7 on 2023-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0006_alter_receita_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
