# Generated by Django 4.1.7 on 2023-06-11 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0011_alter_lista_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2023, 6, 11, 11, 11, 54, 348797)),
        ),
    ]
