# Generated by Django 4.1.7 on 2023-06-11 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0013_alter_lista_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 11, 19, 4, 424707)),
        ),
    ]
