# Generated by Django 4.1.7 on 2023-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Weblist', '0014_alter_lista_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='data',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
